### PR TITLE
Add tracker for active sub-menu for side menu.

### PR DESCRIPTION
**Pull request by phalodi**
fix issue #79 
-Change colour of active sub-menu in side bar, so user can know on which menu currently they are.

### CODE REVIEW

**Comment by LeonorLunatech** [comment]
👍

**Comment by LeonorLunatech** [comment]
I'm testing this now and it does not work for all sub-separators of a submenu. For example, in "Menus" there's the sub-separator to list the menus and another to create a new menu. The active submenu is only visible in the list of menus, and disappears when creating a new menu

**Comment by phalodi** [comment]
@LeonorLunatech Yes because when we need to create a new menu we have to add it in javascript also to works normally.

**Comment by LeonorLunatech** [comment]
@arnieel Given that can do FE, can you try to fix this? or re-implement it? it was not working properly

**Comment by arnieel** [comment]
This should work now. :)

**Comment by LeonorLunatech** [comment]
looks good! merging!

**Pull request merged**
