### PR TITLE
Add reports in admin login

### PR DESCRIPTION
**Pull request by phalodi**
fix issue #88 
-Add functionality for reports between 2 dates like total people, who attend how many Fridays lunch between dates.
-Add reports tab in admin panel.

### CODE REVIEW

**Comment by LeonorLunatech** [comment]
Does this report need a nice print functionality?
Did you ask Shelley if it's OK to have it just in the screen?

**Comment by LeonorLunatech** [comment]
Don't call the count column "number of Fridays", the app is more generic than that. Just call it "count"

**Comment by LeonorLunatech** [comment]
I have added the functionality of exporting the tables into CVS.
I have also done some rework.
@phalodi @vijaykiran could you do a review?

**Comment by pepite** [comment]
I think this will never work. What is needed is to register people *after *they took the meal. This is for financial purpose. This cannot be based on something people plan to do. We need a different issue than that one.

**Comment by Shermans2806** [comment]
All I need for finance is a report with the names of people who had lunch and the names who did not. This does not have to be 100% accurate but if we produce such a list based on what is filled in then it will be good enough for the Tax Office. If we do not have a list then we pay for all employees regardless if they have had lunch or not. So if incidentally someone fills in incorrectly then it is ok. The report can be sent after the period so it is not a guess. I would not like to go around making everyone sign for lunch on paper and prefer an automatic way.

**Comment by pepite** [comment]
Then I can generate a report for 50 random people right?

**Comment by pepite** [comment]
I mean if we were to always order for 50

**Comment by LeonorLunatech** [comment]
Well it will be as reliable as the previous method when using the datum prikker I guess.
I had planned to show how it looks like to @Shermans2806 last Friday but I end up by not going to Rotterdam. 
Does not have the list of people that did not eat. That is really tricky. We are not removing old user from the DB and would really depend on the point in time the reports are generated.

**Comment by arnieel** [comment]
I changed the implementation in a way that the backend will handle the report file generation to an excel spreadsheet.

**Comment by LeonorLunatech** [comment]
Much better 😄 
I just have one note. In `attendees` you forgot the `:`. 
Besides that can you make `Date:`, `Total:`and `Attendess:` bold?

**Pull request merged**
